services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - CLOUDFLARE_ACCOUNT_ID=${CLOUDFLARE_ACCOUNT_ID}
      - NODE_ENV=production
    volumes:
      - sdb_db_data:/app/db
      - sdb_report_data:/app/app/data
    restart: always

volumes:
  sdb_db_data:
  sdb_report_data:
